name: Build and Deploy Site

on:
  schedule:
    # Runs every day at 6:00 AM UTC
    - cron: "0 6 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Deno
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # Build the site
      - name: Build site
        run: deno task lume

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
